LogicalID:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          -
        DisableApiStop: false
        DisableApiTermination: false
        EbsOptimized: false
        ElasticGpuSpecifications:
          -
        ElasticInferenceAccelerators:
          -
        ImageId: "String"
        InstanceInitiatedShutdownBehavior: "String"
        InstanceType: "String"
        KernelId: "String"
        KeyName: "String"
        LicenseSpecifications:
          -
        NetworkInterfaces:
          -
        RamDiskId: "String"
        SecurityGroupIds:
          -
        SecurityGroups:
          -
        TagSpecifications:
          -
        UserData: "String"
      LaunchTemplateName: "String"
      TagSpecifications:
        TagSpecifications
      VersionDescription: "String"